"""
Quality Validator Agent - Employee Monitoring System

Validates and controls the quality of analyses generated by other agents,
provides LLM-powered revision workflows and ensures data accuracy.
"""

import asyncio
import logging
import json
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path

from ..core.base_agent import BaseAgent, AgentConfig, AgentResult
from ..core.llm_client import LLMClient
from ..core.json_memory_store import JSONMemoryStore
from ..core.quality_metrics import QualityMetrics as CoreQualityMetrics
from ..core.config import get_employee_monitoring_config

logger = logging.getLogger(__name__)


class ValidationStatus(Enum):
    """Validation status for analyses."""
    PENDING = "pending"
    VALIDATING = "validating"
    APPROVED = "approved"
    REJECTED = "rejected"
    REVISION_REQUIRED = "revision_required"
    MANUAL_REVIEW = "manual_review"


class ValidationLevel(Enum):
    """Validation levels for different types of analyses."""
    BASIC = "basic"
    STANDARD = "standard"
    STRICT = "strict"
    COMPREHENSIVE = "comprehensive"


@dataclass
class ValidationRule:
    """Rule for validating analysis quality."""
    name: str
    description: str
    weight: float
    threshold: float
    validation_func: callable


@dataclass
class ValidationResult:
    """Result of validation process."""
    status: ValidationStatus
    overall_score: float
    rule_results: Dict[str, Dict[str, Any]]
    issues_found: List[str]
    recommendations: List[str]
    revision_suggestions: Dict[str, Any]
    validation_time: datetime
    validator_agent: str


@dataclass
class QualityMetrics:
    """Quality metrics for analysis."""
    completeness_score: float
    accuracy_score: float
    consistency_score: float
    insight_quality_score: float
    data_integrity_score: float
    overall_quality_score: float


class QualityValidatorAgent(BaseAgent):
    """
    Quality Validator Agent for Employee Monitoring System.
    
    Validates and controls quality by:
    - Applying validation rules to analyses
    - LLM-powered quality assessment
    - Revision workflow management
    - Consistency checking across analyses
    - Automated quality scoring
    - Manual review triggers
    """
    
    def __init__(self, config: Optional[AgentConfig] = None):
        """
        Initialize Quality Validator Agent.
        
        Args:
            config: Agent configuration
        """
        super().__init__(
            config or AgentConfig(
                name="QualityValidatorAgent",
                description="Validates and controls quality of analyses with LLMpowered revision workflow",
                version="1.0.0"
            )
        )
        
        # Initialize components
        self.llm_client = LLMClient()
        self.memory_store = JSONMemoryStore()
        self.quality_metrics = CoreQualityMetrics()
        
        # Load employee monitoring configuration
        self.emp_config = get_employee_monitoring_config()
        self.quality_config = self.emp_config.get('quality', {})
        self.reports_config = self.emp_config.get('reports', {})
        
        # Quality parameters
        self.quality_threshold = self.quality_config.get('threshold', 0.9)
        self.validation_level = ValidationLevel(self.quality_config.get('validation_level', 'standard'))
        self.auto_revision_enabled = self.quality_config.get('auto_revision', True)
        self.max_revision_attempts = self.quality_config.get('max_revision_attempts', 3)
        
        # Validation rules
        self.validation_rules = self._initialize_validation_rules()
        
        # Quality reports directory
        self.quality_reports_dir = Path(self.reports_config.get('quality_reports_dir', './reports/quality'))
        self.quality_reports_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info("QualityValidatorAgent initialized for employee monitoring")
    
    def _initialize_validation_rules(self) -> List[ValidationRule]:
        """Initialize validation rules for different types of analyses."""
        rules = [
            # Data completeness rules
            ValidationRule(
                name="employee_data_completeness",
                description="Ensure all employees have complete data",
                weight=0.2,
                threshold=0.8,
                validation_func=self._validate_employee_data_completeness
            ),
            
            # Data consistency rules
            ValidationRule(
                name="data_consistency",
                description="Check for data consistency across days",
                weight=0.15,
                threshold=0.85,
                validation_func=self._validate_data_consistency
            ),
            
            # Performance accuracy rules
            ValidationRule(
                name="performance_accuracy",
                description="Validate performance calculation accuracy",
                weight=0.15,
                threshold=0.9,
                validation_func=self._validate_performance_accuracy
            ),
            
            # Insight quality rules
            ValidationRule(
                name="insight_quality",
                description="Assess quality and relevance of insights",
                weight=0.2,
                threshold=0.75,
                validation_func=self._validate_insight_quality
            ),
            
            # Data integrity rules
            ValidationRule(
                name="data_integrity",
                description="Check for data integrity and anomalies",
                weight=0.15,
                threshold=0.95,
                validation_func=self._validate_data_integrity
            ),
            
            # Recommendation relevance rules
            ValidationRule(
                name="recommendation_relevance",
                description="Validate relevance and actionability of recommendations",
                weight=0.15,
                threshold=0.8,
                validation_func=self._validate_recommendation_relevance
            )
        ]
        
        return rules
    
    async def execute(self, input_data: Dict[str, Any]) -> AgentResult:
        """
        Execute quality validation for employee monitoring analyses.
        
        Args:
            input_data: Analysis data to validate
            
        Returns:
            AgentResult with validation results and recommendations
        """
        try:
            logger.info("Starting Quality Validation")
            start_time = datetime.now()
            
            # Extract analysis data
            analysis_data = input_data.get('analysis_data', {})
            analysis_type = input_data.get('analysis_type', 'unknown')
            validation_level = ValidationLevel(input_data.get('validation_level', self.validation_level.value))
            
            if not analysis_data:
                return AgentResult(
                    success=False,
                    message="No analysis data provided for validation",
                    data={}
                )
            
            # Step 1: Perform rule-based validation
            validation_result = await self._validate_with_rules(analysis_data, analysis_type, validation_level)
            
            # Step 2: LLM-powered quality assessment
            if validation_result.overall_score < self.quality_threshold or validation_level in [ValidationLevel.STRICT, ValidationLevel.COMPREHENSIVE]:
                await self._enhance_with_llm_validation(analysis_data, validation_result)
            
            # Step 3: Generate quality metrics
            quality_metrics = await self._calculate_quality_metrics(analysis_data, validation_result)
            
            # Step 4: Determine final status and actions
            final_status, actions = await self._determine_final_status(validation_result, quality_metrics)
            validation_result.status = final_status
            
            # Step 5: Save validation report
            await self._save_validation_report(analysis_data, validation_result, quality_metrics)
            
            # Step 6: Update memory store
            await self._update_memory_store(analysis_data, validation_result, quality_metrics)
            
            # Calculate execution time
            execution_time = datetime.now() - start_time
            
            logger.info(f"Quality Validation completed in {execution_time.total_seconds():.2f}s, "
                       f"status: {final_status.value}, score: {validation_result.overall_score:.2f}")
            
            return AgentResult(
                success=True,
                message=f"Validation completed with status: {final_status.value}, score: {validation_result.overall_score:.2f}",
                data={
                    'validation_result': validation_result,
                    'quality_metrics': quality_metrics,
                    'recommended_actions': actions
                },
                metadata={
                    'execution_time': execution_time.total_seconds(),
                    'validation_status': final_status.value,
                    'quality_score': validation_result.overall_score,
                    'analysis_type': analysis_type,
                    'validation_level': validation_level.value
                }
            )
            
        except Exception as e:
            logger.error(f"Quality Validation failed: {e}")
            return AgentResult(
                success=False,
                message=f"Validation failed: {str(e)}",
                data={},
                error=str(e)
            )
    
    async def _validate_with_rules(self, analysis_data: Dict[str, Any], analysis_type: str, validation_level: ValidationLevel) -> ValidationResult:
        """Validate analysis data using rule-based approach."""
        rule_results = {}
        total_score = 0.0
        total_weight = 0.0
        
        for rule in self.validation_rules:
            try:
                # Apply rule validation
                rule_score, rule_issues, rule_recommendations = await rule.validation_func(analysis_data, analysis_type)
                
                # Adjust threshold based on validation level
                adjusted_threshold = self._adjust_threshold(rule.threshold, validation_level)
                
                # Determine if rule passed
                rule_passed = rule_score >= adjusted_threshold
                
                rule_results[rule.name] = {
                    'score': rule_score,
                    'threshold': adjusted_threshold,
                    'passed': rule_passed,
                    'weight': rule.weight,
                    'issues': rule_issues,
                    'recommendations': rule_recommendations
                }
                
                total_score += rule_score * rule.weight
                total_weight += rule.weight
                
            except Exception as e:
                logger.warning(f"Validation rule '{rule.name}' failed: {e}")
                rule_results[rule.name] = {
                    'score': 0.0,
                    'threshold': rule.threshold,
                    'passed': False,
                    'weight': rule.weight,
                    'issues': [f"Rule execution failed: {str(e)}"],
                    'recommendations': []
                }
                total_weight += rule.weight
        
        # Calculate overall score
        overall_score = total_score / total_weight if total_weight > 0 else 0.0
        
        # Collect all issues and recommendations
        all_issues = []
        all_recommendations = []
        
        for rule_result in rule_results.values():
            all_issues.extend(rule_result.get('issues', []))
            all_recommendations.extend(rule_result.get('recommendations', []))
        
        return ValidationResult(
            status=ValidationStatus.PENDING,
            overall_score=overall_score,
            rule_results=rule_results,
            issues_found=all_issues,
            recommendations=all_recommendations,
            revision_suggestions={},
            validation_time=datetime.now(),
            validator_agent=self.config.name
        )
    
    def _adjust_threshold(self, base_threshold: float, validation_level: ValidationLevel) -> float:
        """Adjust validation threshold based on validation level."""
        adjustments = {
            ValidationLevel.BASIC: -0.15,
            ValidationLevel.STANDARD: 0.0,
            ValidationLevel.STRICT: 0.1,
            ValidationLevel.COMPREHENSIVE: 0.2
        }
        
        adjustment = adjustments.get(validation_level, 0.0)
        return min(1.0, max(0.0, base_threshold + adjustment))
    
    async def _validate_employee_data_completeness(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Validate employee data completeness."""
        issues = []
        recommendations = []
        
        # Check for employee data based on analysis type
        if analysis_type in ['task_analysis', 'weekly_report']:
            employees_data = analysis_data.get('employees_progress') or analysis_data.get('employee_summaries', {})
            
            if not employees_data:
                return 0.0, ["No employee data found"], ["Add employee data to analysis"]
            
            # Check for missing required fields
            required_fields = {
                'task_analysis': ['employee_name', 'performance_rating', 'completion_rate'],
                'meeting_analysis': ['employee_name', 'engagement_score', 'activity_rating'],
                'weekly_report': ['task_metrics', 'meeting_metrics']
            }
            
            missing_fields_count = 0
            total_checks = 0
            
            for employee, data in employees_data.items():
                required = required_fields.get(analysis_type, [])
                for field in required:
                    total_checks += 1
                    if field not in data or data[field] is None:
                        missing_fields_count += 1
                        issues.append(f"Missing '{field}' for employee {employee}")
            
            # Calculate completeness score
            completeness_score = 1.0 - (missing_fields_count / max(total_checks, 1))
            
            if completeness_score < 0.8:
                recommendations.append("Ensure all required employee data fields are populated")
            
            return completeness_score, issues, recommendations
        
        return 0.8, [], ["Employee data completeness validation not applicable for this analysis type"]
    
    async def _validate_data_consistency(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Validate data consistency across the analysis."""
        issues = []
        recommendations = []
        
        try:
            # Check for date consistency
            analysis_date = analysis_data.get('analysis_date') or analysis_data.get('generated_at')
            if analysis_date and isinstance(analysis_date, str):
                try:
                    datetime.fromisoformat(analysis_date.replace('Z', '+00:00'))
                except ValueError:
                    issues.append("Invalid date format in analysis data")
            
            # Check for numerical consistency
            if analysis_type == 'task_analysis':
                employees_progress = analysis_data.get('employees_progress', {})
                for employee, data in employees_progress.items():
                    # Check that completion rate is between 0 and 1
                    completion_rate = data.get('completion_rate', 0)
                    if not (0 <= completion_rate <= 1):
                        issues.append(f"Invalid completion rate for {employee}: {completion_rate}")
                    
                    # Check that performance rating is between 1 and 10
                    performance_rating = data.get('performance_rating', 0)
                    if not (1 <= performance_rating <= 10):
                        issues.append(f"Invalid performance rating for {employee}: {performance_rating}")
            
            # Calculate consistency score
            consistency_score = 1.0 - (len(issues) / 10.0)  # Assume max 10 potential issues
            consistency_score = max(0.0, consistency_score)
            
            if consistency_score < 0.8:
                recommendations.append("Review and fix data consistency issues")
            
            return consistency_score, issues, recommendations
            
        except Exception as e:
            logger.warning(f"Data consistency validation failed: {e}")
            return 0.5, [f"Consistency validation error: {str(e)}"], ["Review data structure and formats"]
    
    async def _validate_performance_accuracy(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Validate performance calculation accuracy."""
        issues = []
        recommendations = []
        
        if analysis_type == 'task_analysis':
            employees_progress = analysis_data.get('employees_progress', {})
            
            for employee, data in employees_progress.items():
                # Recalculate completion rate to verify
                total_tasks = data.get('total_tasks', 0)
                completed_tasks = data.get('completed_tasks', 0)
                
                if total_tasks > 0:
                    calculated_rate = completed_tasks / total_tasks
                    reported_rate = data.get('completion_rate', 0)
                    
                    # Allow small floating point differences
                    if abs(calculated_rate - reported_rate) > 0.01:
                        issues.append(f"Completion rate mismatch for {employee}: calculated {calculated_rate:.3f}, reported {reported_rate:.3f}")
                
                # Check story points consistency
                total_sp = data.get('total_story_points', 0)
                completed_sp = data.get('completed_story_points', 0)
                
                if total_sp > 0 and completed_sp > total_sp:
                    issues.append(f"Completed story points exceed total for {employee}: {completed_sp} > {total_sp}")
        
        # Calculate accuracy score
        accuracy_score = 1.0 - (len(issues) / 5.0)  # Assume max 5 potential accuracy issues
        accuracy_score = max(0.0, accuracy_score)
        
        if accuracy_score < 0.9:
            recommendations.append("Review and correct performance calculation formulas")
        
        return accuracy_score, issues, recommendations
    
    async def _validate_insight_quality(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Validate quality and relevance of insights."""
        issues = []
        recommendations = []
        
        try:
            insights = analysis_data.get('team_insights', [])
            
            if not insights:
                return 0.3, ["No team insights provided"], ["Add meaningful team insights to the analysis"]
            
            # Check insight quality factors
            quality_factors = {
                'length': 0,
                'specificity': 0,
                'actionability': 0,
                'relevance': 0
            }
            
            for insight in insights:
                # Length check - insights should be substantial
                if len(insight) >= 10:
                    quality_factors['length'] += 1
                
                # Specificity check - should contain specific data
                if any(keyword in insight.lower() for keyword in ['%', 'score', 'rating', 'tasks', 'meetings']):
                    quality_factors['specificity'] += 1
                
                # Actionability check - should suggest actions
                if any(keyword in insight.lower() for keyword in ['improve', 'increase', 'reduce', 'implement', 'consider']):
                    quality_factors['actionability'] += 1
                
                # Relevance check - should be relevant to employee monitoring
                if any(keyword in insight.lower() for keyword in ['team', 'employee', 'performance', 'engagement', 'productivity']):
                    quality_factors['relevance'] += 1
            
            # Calculate quality score
            if insights:
                for factor in quality_factors:
                    quality_factors[factor] = quality_factors[factor] / len(insights)
                
                insight_quality = sum(quality_factors.values()) / len(quality_factors)
            else:
                insight_quality = 0.0
            
            if insight_quality < 0.75:
                if quality_factors['length'] < 0.5:
                    recommendations.append("Make insights more detailed and specific")
                if quality_factors['specificity'] < 0.5:
                    recommendations.append("Include specific metrics and data in insights")
                if quality_factors['actionability'] < 0.5:
                    recommendations.append("Make insights more actionable and practical")
                if quality_factors['relevance'] < 0.5:
                    recommendations.append("Ensure insights are relevant to employee monitoring")
            
            return insight_quality, issues, recommendations
            
        except Exception as e:
            logger.warning(f"Insight quality validation failed: {e}")
            return 0.5, [f"Insight validation error: {str(e)}"], ["Review insight generation process"]
    
    async def _validate_data_integrity(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Check for data integrity and anomalies."""
        issues = []
        recommendations = []
        
        try:
            # Check for null values in critical fields
            critical_fields = ['analysis_date'] if analysis_type == 'unknown' else []
            
            if analysis_type == 'task_analysis':
                critical_fields.extend(['total_employees', 'employees_progress'])
            elif analysis_type == 'meeting_analysis':
                critical_fields.extend(['total_employees', 'employees_activity'])
            elif analysis_type == 'weekly_report':
                critical_fields.extend(['employee_summaries', 'task_summary', 'meeting_summary'])
            
            null_count = 0
            for field in critical_fields:
                if field not in analysis_data or analysis_data[field] is None:
                    null_count += 1
                    issues.append(f"Critical field '{field}' is missing or null")
            
            # Check for data anomalies
            if analysis_type == 'task_analysis':
                employees_progress = analysis_data.get('employees_progress', {})
                for employee, data in employees_progress.items():
                    # Check for negative values
                    if data.get('total_tasks', 0) < 0:
                        issues.append(f"Negative task count for {employee}")
                    if data.get('completion_rate', 0) < 0:
                        issues.append(f"Negative completion rate for {employee}")
            
            # Calculate integrity score
            integrity_score = 1.0 - (null_count / max(len(critical_fields), 1))
            integrity_score = max(0.0, integrity_score)
            
            if integrity_score < 0.95:
                recommendations.append("Review and fix data integrity issues")
            
            return integrity_score, issues, recommendations
            
        except Exception as e:
            logger.warning(f"Data integrity validation failed: {e}")
            return 0.5, [f"Integrity validation error: {str(e)}"], ["Review data structure and null values"]
    
    async def _validate_recommendation_relevance(self, analysis_data: Dict[str, Any], analysis_type: str) -> Tuple[float, List[str], List[str]]:
        """Validate relevance and actionability of recommendations."""
        issues = []
        recommendations = []
        
        try:
            recommendations_list = analysis_data.get('recommendations', [])
            
            if not recommendations_list:
                return 0.3, ["No recommendations provided"], ["Add actionable recommendations to the analysis"]
            
            # Check recommendation quality factors
            quality_factors = {
                'specificity': 0,
                'actionability': 0,
                'relevance': 0,
                'feasibility': 0
            }
            
            for recommendation in recommendations_list:
                # Specificity check - should be specific and measurable
                if len(recommendation) >= 15 and any(char.isdigit() for char in recommendation):
                    quality_factors['specificity'] += 1
                
                # Actionability check - should start with action verbs
                action_verbs = ['implement', 'create', 'develop', 'establish', 'improve', 'increase', 'reduce', 'enhance']
                if any(verb in recommendation.lower() for verb in action_verbs):
                    quality_factors['actionability'] += 1
                
                # Relevance check - should be relevant to the analysis
                relevant_keywords = ['employee', 'team', 'performance', 'meeting', 'task', 'productivity', 'engagement']
                if any(keyword in recommendation.lower() for keyword in relevant_keywords):
                    quality_factors['relevance'] += 1
                
                # Feasibility check - should be practical
                if len(recommendation) <= 200:  # Not too long to be impractical
                    quality_factors['feasibility'] += 1
            
            # Calculate quality score
            if recommendations_list:
                for factor in quality_factors:
                    quality_factors[factor] = quality_factors[factor] / len(recommendations_list)
                
                recommendation_quality = sum(quality_factors.values()) / len(quality_factors)
            else:
                recommendation_quality = 0.0
            
            if recommendation_quality < 0.8:
                if quality_factors['specificity'] < 0.5:
                    recommendations.append("Make recommendations more specific and measurable")
                if quality_factors['actionability'] < 0.5:
                    recommendations.append("Start recommendations with clear action verbs")
                if quality_factors['relevance'] < 0.5:
                    recommendations.append("Ensure recommendations are relevant to employee monitoring")
                if quality_factors['feasibility'] < 0.5:
                    recommendations.append("Make recommendations more practical and feasible")
            
            return recommendation_quality, issues, recommendations
            
        except Exception as e:
            logger.warning(f"Recommendation relevance validation failed: {e}")
            return 0.5, [f"Recommendation validation error: {str(e)}"], ["Review recommendation generation process"]
    
    async def _enhance_with_llm_validation(self, analysis_data: Dict[str, Any], validation_result: ValidationResult) -> None:
        """Enhance validation with LLM-powered quality assessment."""
        try:
            # Prepare data for LLM validation
            llm_input = self._prepare_llm_validation_input(analysis_data, validation_result)
            
            # For now, add placeholder LLM insights
            # In real implementation, this would call LLM service
            validation_result.revision_suggestions['llm_insights'] = "LLM validation insights would be added here"
            validation_result.revision_suggestions['automated_improvements'] = [
                "Consider adding more specific metrics to insights",
                "Review recommendation actionability",
                "Enhance data visualization suggestions"
            ]
            
        except Exception as e:
            logger.warning(f"Failed to enhance with LLM validation: {e}")
    
    def _prepare_llm_validation_input(self, analysis_data: Dict[str, Any], validation_result: ValidationResult) -> str:
        """Prepare data for LLM validation."""
        parts = [
            f"Quality Validation Request - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"Current Quality Score: {validation_result.overall_score:.2f}",
            f"Issues Found: {len(validation_result.issues_found)}",
            "",
            "Analysis Summary:",
            f"  Analysis Type: {analysis_data.get('analysis_type', 'unknown')}",
            f"  Employees Analyzed: {len(analysis_data.get('employees_progress') or analysis_data.get('employee_summaries', {}))}",
            f"  Insights Generated: {len(analysis_data.get('team_insights', []))}",
            f"  Recommendations: {len(analysis_data.get('recommendations', []))}",
            "",
            "Key Issues:",
        ]
        
        for issue in validation_result.issues_found[:5]:  # Limit to top 5 issues
            parts.append(f"  - {issue}")
        
        return "\n".join(parts)
    
    async def _calculate_quality_metrics(self, analysis_data: Dict[str, Any], validation_result: ValidationResult) -> QualityMetrics:
        """Calculate comprehensive quality metrics."""
        try:
            # Extract scores from rule results
            rule_scores = {
                'employee_data_completeness': 0.0,
                'data_consistency': 0.0,
                'performance_accuracy': 0.0,
                'insight_quality': 0.0,
                'data_integrity': 0.0,
                'recommendation_relevance': 0.0
            }
            
            for rule_name, rule_result in validation_result.rule_results.items():
                if rule_name in rule_scores:
                    rule_scores[rule_name] = rule_result.get('score', 0.0)
            
            # Calculate quality metrics
            completeness_score = rule_scores['employee_data_completeness']
            accuracy_score = rule_scores['performance_accuracy']
            consistency_score = rule_scores['data_consistency']
            insight_quality_score = rule_scores['insight_quality']
            data_integrity_score = rule_scores['data_integrity']
            
            # Calculate overall quality score
            overall_quality_score = (
                completeness_score * 0.2 +
                accuracy_score * 0.2 +
                consistency_score * 0.15 +
                insight_quality_score * 0.2 +
                data_integrity_score * 0.15 +
                rule_scores['recommendation_relevance'] * 0.1
            )
            
            return QualityMetrics(
                completeness_score=completeness_score,
                accuracy_score=accuracy_score,
                consistency_score=consistency_score,
                insight_quality_score=insight_quality_score,
                data_integrity_score=data_integrity_score,
                overall_quality_score=overall_quality_score
            )
            
        except Exception as e:
            logger.warning(f"Failed to calculate quality metrics: {e}")
            return QualityMetrics(
                completeness_score=0.5,
                accuracy_score=0.5,
                consistency_score=0.5,
                insight_quality_score=0.5,
                data_integrity_score=0.5,
                overall_quality_score=0.5
            )
    
    async def _determine_final_status(self, validation_result: ValidationResult, quality_metrics: QualityMetrics) -> Tuple[ValidationStatus, List[str]]:
        """Determine final validation status and recommended actions."""
        actions = []
        
        # Define status thresholds
        if quality_metrics.overall_quality_score >= 0.9 and len(validation_result.issues_found) == 0:
            status = ValidationStatus.APPROVED
            actions.append("Analysis approved for publication")
        
        elif quality_metrics.overall_quality_score >= 0.8 and len(validation_result.issues_found) <= 2:
            status = ValidationStatus.APPROVED
            actions.append("Analysis approved with minor recommendations")
            actions.extend(validation_result.recommendations[:3])
        
        elif quality_metrics.overall_quality_score >= 0.7:
            status = ValidationStatus.REVISION_REQUIRED
            actions.append("Revision required before approval")
            actions.extend(validation_result.recommendations[:5])
            
            if self.auto_revision_enabled:
                actions.append("Consider enabling auto-revision workflow")
        
        elif quality_metrics.overall_quality_score >= 0.5:
            status = ValidationStatus.MANUAL_REVIEW
            actions.append("Manual review required due to quality concerns")
            actions.extend(validation_result.issues_found[:3])
        
        else:
            status = ValidationStatus.REJECTED
            actions.append("Analysis rejected due to poor quality")
            actions.append("Requires comprehensive review and regeneration")
            actions.extend(validation_result.issues_found[:5])
        
        return status, actions
    
    async def _save_validation_report(self, analysis_data: Dict[str, Any], validation_result: ValidationResult, quality_metrics: QualityMetrics) -> None:
        """Save validation report to file system."""
        try:
            # Create filename with timestamp
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            analysis_type = analysis_data.get('analysis_type', 'unknown')
            report_file = self.quality_reports_dir / f"validation_{analysis_type}_{timestamp}.json"
            
            # Prepare validation data
            validation_report = {
                'validation_timestamp': validation_result.validation_time.isoformat(),
                'validator_agent': validation_result.validator_agent,
                'analysis_type': analysis_data.get('analysis_type', 'unknown'),
                'analysis_id': analysis_data.get('id', f"analysis_{timestamp}"),
                
                # Validation results
                'validation_status': validation_result.status.value,
                'overall_score': validation_result.overall_score,
                'rule_results': validation_result.rule_results,
                
                # Issues and recommendations
                'issues_found': validation_result.issues_found,
                'recommendations': validation_result.recommendations,
                'revision_suggestions': validation_result.revision_suggestions,
                
                # Quality metrics
                'quality_metrics': {
                    'completeness_score': quality_metrics.completeness_score,
                    'accuracy_score': quality_metrics.accuracy_score,
                    'consistency_score': quality_metrics.consistency_score,
                    'insight_quality_score': quality_metrics.insight_quality_score,
                    'data_integrity_score': quality_metrics.data_integrity_score,
                    'overall_quality_score': quality_metrics.overall_quality_score
                },
                
                # Analysis summary
                'analysis_summary': {
                    'employees_analyzed': len(analysis_data.get('employees_progress') or analysis_data.get('employee_summaries', {})),
                    'insights_generated': len(analysis_data.get('team_insights', [])),
                    'recommendations_generated': len(analysis_data.get('recommendations', []))
                }
            }
            
            # Save to JSON file
            with open(report_file, 'w', encoding='utf-8') as f:
                json.dump(validation_report, f, indent=2, ensure_ascii=False)
            
            logger.info(f"Validation report saved to {report_file}")
            
        except Exception as e:
            logger.error(f"Failed to save validation report: {e}")
    
    async def _update_memory_store(self, analysis_data: Dict[str, Any], validation_result: ValidationResult, quality_metrics: QualityMetrics) -> None:
        """Update memory store with validation results."""
        try:
            validation_record = {
                'validation_timestamp': validation_result.validation_time.isoformat(),
                'validator_agent': validation_result.validator_agent,
                'analysis_type': analysis_data.get('analysis_type', 'unknown'),
                'validation_status': validation_result.status.value,
                'overall_score': validation_result.overall_score,
                'quality_metrics': {
                    'completeness_score': quality_metrics.completeness_score,
                    'accuracy_score': quality_metrics.accuracy_score,
                    'consistency_score': quality_metrics.consistency_score,
                    'insight_quality_score': quality_metrics.insight_quality_score,
                    'data_integrity_score': quality_metrics.data_integrity_score,
                    'overall_quality_score': quality_metrics.overall_quality_score
                },
                'issues_count': len(validation_result.issues_found),
                'recommendations_count': len(validation_result.recommendations),
                'rules_passed': sum(1 for rule in validation_result.rule_results.values() if rule.get('passed', False)),
                'total_rules': len(validation_result.rule_results)
            }
            
            await self.memory_store.save_record(
                data=validation_record,
                record_type='quality_validation',
                record_id=f"{analysis_data.get('analysis_type', 'unknown')}_{validation_result.validation_time.strftime('%Y%m%d_%H%M%S')}",
                source='quality_validator_agent'
            )
            
            logger.info("Updated memory store with validation results")
            
        except Exception as e:
            logger.error(f"Failed to update memory store: {e}")
    
    async def validate_analysis(self, analysis_data: Dict[str, Any], analysis_type: str = "unknown", validation_level: str = "standard") -> Dict[str, Any]:
        """
        Validate analysis data and return validation results.
        
        This method provides a simplified interface for validation that can be used
        by other agents in the system.
        
        Args:
            analysis_data: Analysis data to validate
            analysis_type: Type of analysis (task_analysis, meeting_analysis, weekly_report)
            validation_level: Validation level (basic, standard, strict, comprehensive)
            
        Returns:
            Dictionary with validation results
        """
        try:
            logger.info(f"Starting analysis validation for type: {analysis_type}")
            
            # Convert object to dict if needed
            if hasattr(analysis_data, '__dict__'):
                # Handle dataclass objects
                analysis_dict = asdict(analysis_data) if hasattr(analysis_data, '__dataclass_fields__') else analysis_data.__dict__
            elif hasattr(analysis_data, 'get'):
                # Already a dict-like object
                analysis_dict = analysis_data
            else:
                # Try to convert to dict
                try:
                    analysis_dict = dict(analysis_data)
                except (TypeError, ValueError):
                    # Last resort - wrap in dict
                    analysis_dict = {'data': analysis_data}
            
            # Prepare input data for validation
            input_data = {
                'analysis_data': analysis_dict,
                'analysis_type': analysis_type,
                'validation_level': validation_level
            }
            
            # Execute validation
            result = await self.execute(input_data)
            
            if result.success:
                validation_result = result.data['validation_result']
                quality_metrics = result.data['quality_metrics']
                actions = result.data['recommended_actions']
                
                return {
                    'success': True,
                    'validation_status': validation_result.status.value,
                    'overall_score': validation_result.overall_score,
                    'quality_metrics': {
                        'completeness_score': quality_metrics.completeness_score,
                        'accuracy_score': quality_metrics.accuracy_score,
                        'consistency_score': quality_metrics.consistency_score,
                        'insight_quality_score': quality_metrics.insight_quality_score,
                        'data_integrity_score': quality_metrics.data_integrity_score,
                        'overall_quality_score': quality_metrics.overall_quality_score
                    },
                    'issues_found': validation_result.issues_found,
                    'recommendations': validation_result.recommendations,
                    'recommended_actions': actions,
                    'execution_time': result.metadata.get('execution_time', 0),
                    'rule_results': validation_result.rule_results
                }
            else:
                return {
                    'success': False,
                    'error': result.message,
                    'error_details': result.error
                }
                
        except Exception as e:
            logger.error(f"Analysis validation failed: {e}")
            return {
                'success': False,
                'error': f"Validation failed: {str(e)}",
                'error_details': str(e)
            }
    
    async def get_health_status(self) -> Dict[str, Any]:
        """Get agent health status."""
        try:
            llm_available = await self.llm_client.is_available()
            memory_available = self.memory_store.is_healthy()
            
            return {
                'agent_name': self.config.name,
                'status': 'healthy' if llm_available and memory_available else 'degraded',
                'llm_client': 'available' if llm_available else 'unavailable',
                'memory_store': 'healthy' if memory_available else 'unhealthy',
                'config_loaded': bool(self.emp_config),
                'validation_rules_count': len(self.validation_rules),
                'quality_threshold': self.quality_threshold,
                'validation_level': self.validation_level.value,
                'auto_revision_enabled': self.auto_revision_enabled,
                'quality_reports_directory': str(self.quality_reports_dir),
                'last_check': datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Health check failed: {e}")
            return {
                'agent_name': self.config.name,
                'status': 'error',
                'error': str(e),
                'last_check': datetime.now().isoformat()
            }
